### PR TITLE
Landing page - Updates

### PR DESCRIPTION
**Pull request by cedricwaxwing**
**Note:** I'm having trouble with my fleek builds, but I'm wondering if it's just an issue related to the `gh-pages` commands. I am using `yarn build` as the build command, and it builds out the home page without any issues, but the `/signup` page (or any other routes I tried adding earlier) do not work and I get the following error:

`ipfs resolve -r /ipfs/bafybeihjfziewd7ymr3eotnz4kre7h4rtk2tmyqs6ay7pozhmprv4t5gzu/signup: no link named "signup" under bafybeihjfziewd7ymr3eotnz4kre7h4rtk2tmyqs6ay7pozhmprv4t5gzu`

If someone can take a look at my [App.tsx](https://github.com/polywrap/landing-page/compare/master...cedricwaxwing:v2-1#diff-26ad4b834941d9b19ebf9db8082bd202aaf72ea0ddea85f5a8a0cb3c729cc6f2) and confirm I've set up the routing that would be appreciated.

### CODE REVIEW

**Comment by cedricwaxwing** [comment]
@kev-ngo I sorted out the NavBar issue (I just renamed it to Header and that resolved it). But I am still getting the same routing issue when I deploy. Could you try deploying from the polywrap:master version?

**Comment by krisbitney** [comment]
BrowserRouter doesn't work properly with static sites unless you can add additional server-side configuration. You can use HashRouter to resolve your problem.

HashRouter works a little bit differently from BrowserRouter. You'll want to set an onClick like that pushes the next page onto the history stack provided by React Router's useHistory() hook. Here's an example: https://github.com/dOrgTech/landing-page-v2/blob/dev/src/components/HeaderDesktop.tsx#L92

See: 
https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing
https://stackoverflow.com/questions/9184959/rewriting-nginx-for-pushstate-urls/28886464#28886464

**Comment by cedricwaxwing** [comment]
Thanks so much @krisbitney! That was the issue. I'm still figuring out the routing side of react, but this helped clarify things quite a bit.

@kev-ngo @rihp the build and deployment worked, and this is ready for review now.

**Comment by dOrgJelli** [comment]
Looks great @cedricwaxwing! Merging this into a separate branch (other than master) to make some minor changes & test further.

**Pull request merged**
